export default function Head() {
  return (
    <>
      <title>Home | Moonwish Studios</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/brand/Logo.svg" />
      <meta
        name="description"
        content="Moonwish Studios designs modern and professional websites for your business. We take care of developing the website using technologies and creative designs to build your business a strong online prescence"
      />
    </>
  )
}
