export default function Head() {
  return (
    <>
      <title>Moonwish Studios</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/brand/Logo.svg" />
    </>
  )
}
